#! /usr/bin/env python3

from sklearn import metrics

labels = [0,0,0,1,0,1,1,0,1,1]
classifier_probs = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.99]

fpr, tpr, thresh1 = metrics.roc_curve(labels, classifier_probs)

print (metrics.auc(fpr, tpr))
